version: '3.1'
services:

  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root 

  mongo-express:
    image: mongo-express
    restart: always
    links:
      - mongodb
    ports:
      - 8181:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root 

volumes:
  mongodb: